students = c("Aiko Liu",
             "Anne Song",
             "Ben Townson",
             "Bernard Ong",
             "Bin Fang",
             "Charles Leung",
             "Chia-An Anne Chen",
             "Christian Holmes",
             "Chuan Sun",
             "Danli Zeng",
             "David Steinmetz",
             "Deepak Khurana",
             "Diego De Lazzari",
             "Gregory Domingo",
             "Jiaxu Luo",
             "Jielei Zhu",
             "Jingyu Zhang",
             "Johann Jurgen de Jager",
             "Jonathan Liu",
             "Le Wei",
             "Linlin Cheng",
             "Miaozhi Trinity Yu",
             "Nanda Trichy Rajarathinam",
             "Ricky Yue",
             "Samriddhi Shakya",
             "Sharan Duggal",
             "Shu Liu",
             "Shuheng Li",
             "Shuo Zhang",
             "Shuye Han",
             "Spencer Stebbins",
             "Tyler Knutson",
             "Tzu-yu Amy Chen",
             "Venkatesh Subramaniam",
             "William Bartlett",
             "Yunrou Gong")

categories = c(rep("Team Generalized Linear Models", 6),
               rep("Team Principal Component Analysis", 6),
               rep("Team Ridge & Lasso Regression", 6),
               rep("Team Cluster Analysis", 6),
               rep("Team Trees", 6),
               rep("Team Support Vector Machines", 6))

set.seed(0)
teams =  sample(sample(sample(sample(sample(categories)))))
cbind(students, teams)[order(teams), ]